/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_md_5_bungee_AESCipher */

#ifndef _Included_net_md_5_bungee_AESCipher
#define _Included_net_md_5_bungee_AESCipher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_md_5_bungee_AESCipher
 * Method:    init
 * Signature: ([BZ)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_AESCipher_init
  (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     net_md_5_bungee_AESCipher
 * Method:    cipher
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_net_md_15_bungee_AESCipher_cipher
  (JNIEnv *, jobject, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
